name: CI/CD pipeline

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.6.0
      
      - name: Mavne Build
        run: |
          mvn --version
          mvn clean package

      - name: Build the Docker image
        run: docker build --tag vigneshsweekaran/hello-world-github-actions:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: docker push vigneshsweekaran/kubectl:latest
          
